### ISSUE TITLE
Example doesn't run: can't import Emacs

### ISSUE THREAD

**Issue by notuntoward** [jlumpe/pyorg#4]
The first example in the package doc has the code

```
from emacs import Emacs
emacs = Emacs.client()
emacs.getresult('(+ 1 2)')
```
But when I run it, I get the error

```
----> [3](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#ch0000000untitled?line=2) from emacs import Emacs
      [4](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#ch0000000untitled?line=3) emacs = Emacs.client()
      [5](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#ch0000000untitled?line=4) emacs.getresult('(+ 1 2)')

ImportError: cannot import name 'Emacs' from 'emacs' (c:\Users\scott\miniconda3\lib\site-packages\emacs\__init__.py)
```

This is after I've also installed the `python-emacs` library, which works.  For example, I can run this successfully

```
from emacs import EmacsBatch
emacs = EmacsBatch(args=['-Q']) 
emacs.eval('(+ 1 2)')
```
Also, I'm not certain if `pyorg` requires `python-emacs`, and if so, if pip installing `pyorg` should install this dependency automatically.

**Comment by gcoladon** [comment]
I just ran into this problem myself. When I installed pyorg via pip, I got version 0.18, which had the above problem. Then I tried installing it via git clone, and I got version 0.20. I tried a different approach to getting things to work, and ended up hitting this problem: 

```
>>> from emacs import EmacsClient
>>> emacs = EmacsClient()
>>> from pyorg import Org
>>> org = Org(emacs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/greg/src/pyorg/pyorg/interface.py", line 30, in __init__
    self._setup_emacs()
  File "/Users/greg/src/pyorg/pyorg/interface.py", line 42, in _setup_emacs
    self.emacs.eval(E.require(E.Q('pyorg')))
  File "/usr/local/lib/python3.10/site-packages/emacs/elisp/dsl.py", line 24, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ElispDSL' object has no attribute 'Q'
>>> 
```
